# Importing libraries

In [1]:
import pandas as pd
import numpy as np

# Importing the dataset

## La latina

In [2]:
df_latina = pd.read_csv(r'C:/Users/cex/PycharmProjects/idealista_scrape/idealista/idealista/idealista_la_latina.csv')
df_latina['Distric'] = 'La Latina'

## Chamartin

In [3]:
df_chamartin = pd.read_csv(r'C:/Users/cex/PycharmProjects/idealista_scrape/idealista/idealista/idealista_chamartin.csv')
df_chamartin['Distric'] = 'Chamartin'

## Chueca

In [4]:
df_chueca = pd.read_csv(r'C:/Users/cex/PycharmProjects/idealista_scrape/idealista/idealista/idealista_chueca.csv')
df_chueca['Distric'] = 'Chueca'

## Lavapies

In [5]:
df_lavapies = pd.read_csv(r'C:/Users/cex/PycharmProjects/idealista_scrape/idealista/idealista/idealista_lavapies.csv')
df_lavapies['Distric'] = 'Lavapies'

## Malasaña

In [6]:
df_malasaña = pd.read_csv(r'C:/Users/cex/PycharmProjects/idealista_scrape/idealista/idealista/idealista_malasaña.csv')
df_malasaña['Distric'] = 'Malasaña'

## Moncloa

In [7]:
df_moncloa = pd.read_csv(r'C:/Users/cex/PycharmProjects/idealista_scrape/idealista/idealista/idealista_moncloa.csv')
df_moncloa['Distric'] = 'Moncloa'

# Joining the 6 dataframes in one

In [8]:
pdList = [df_chamartin,df_chueca,df_latina,df_lavapies,df_malasaña,df_moncloa]  # List of your dataframes
df = pd.concat(pdList)

In [9]:
df

,title,price,rooms,mtts,floor,link,description,Distric
0,"Piso en calle López de Hoyos, 153, Ciudad Jard...",1.2,1 hab.,76 m²,Planta 4ª exterior con ascensor,/inmueble/98637619/,"\nPiso situado en la zona de Alfonso XIII, con...",Chamartin
1,"Piso en pasaje San Pedro, 9, Prosperidad, Madrid",750.0,1 hab.,60 m²,Planta 6ª exterior con ascensor,/inmueble/98538159/,\nLa vivienda tiene cocina independiente y sal...,Chamartin
2,"Piso en calle de Vinaroz, 16, Ciudad Jardín, M...",925.0,1 hab.,55 m²,Planta 1ª exterior con ascensor,/inmueble/98635897/,"\nApartamento en casa con jardin, proximo al a...",Chamartin
3,"Piso en calle Rafael Salgado, Bernabéu-Hispano...",2.8,5 hab.,202 m²,Planta 5ª exterior con ascensor,/inmueble/97596364/,\nVIVIR A LO GRANDE EN EL CORAZÓN DE CHAMARTÍN...,Chamartin
4,"Piso en calle de Pradillo, 13, Ciudad Jardín, ...",1.4,2 hab.,95 m²,Planta 6ª exterior con ascensor,/inmueble/98642139/,\nPrecioso y luminoso piso entre las zonas de ...,Chamartin
...,...,...,...,...,...,...,...,...
558,"Estudio en avenida de la Osa Mayor, 57, Aravac...",750.0,55 m²,Planta 1ª exterior sin ascensor,NaN,/inmueble/91089733/,"\nAire acondicionado, parque recién reformado.\n",Moncloa
559,"Piso en avenida del Talgo, 220, Aravaca, Madrid",1.8,1 hab.,59 m²,Planta 1ª exterior con ascensor,/inmueble/94651456/,\nPrecioso apartamento recién pintado y listo ...,Moncloa
560,"Piso en calle San Restituto, 51, Valdezarza, M...",1.8,2 hab.,98 m²,Planta 6ª exterior con ascensor,/inmueble/27957885/,\nCalidades de lujo. 2 dormitorios. Cocina tot...,Moncloa
561,"Piso en calle Isla de Oza, 76, Ciudad Universi...",1.5,3 hab.,87 m²,Planta 1ª exterior con ascensor,/inmueble/1986527/,\nAbstenerse agencias comunidad incluida en el...,Moncloa
562,"Piso en calle del Tutor, Argüelles, Madrid",3.4,6 hab.,220 m²,Planta 5ª exterior con ascensor,/inmueble/95275218/,\nTODOS LOS GASTOS INCLUIDOS /MAD Housing alqu...,Moncloa

In [10]:
df['Distric'].value_counts()

Chueca       566
Malasaña     565
La Latina    563
Lavapies     563
Moncloa      563
Chamartin    562
Name: Distric, dtype: int64

As you can see the number of districs is almost the same, meaning they were copied very well.

# Create a column to separate the type of housing

In [11]:
df['Type'] = 'whatever'

In [12]:
df.loc[df["title"].str.contains("Piso", case=True), "Type"] = "Flat"
df.loc[df["title"].str.contains("Estudio", case=True), "Type"] = "Studio"
df.loc[df["title"].str.contains("Ático", case=True), "Type"] = "Attic"
df.loc[df["title"].str.contains("Dúplex", case=True), "Type"] = "Duplex"
#Can also be used df['Compare'] = df.apply(lambda x: 'Yes' if x['DEPTH'] in x['Description'] else 'No',axis=1)

In [13]:
df['Type'].value_counts()

Flat        2730
whatever     192
Attic        185
Studio       150
Duplex       125
Name: Type, dtype: int64

# Drop the whatever rows

In [14]:
 df = df.loc[~(df['Type'] == 'whatever')]

In [15]:
df

,title,price,rooms,mtts,floor,link,description,Distric,Type
0,"Piso en calle López de Hoyos, 153, Ciudad Jard...",1.2,1 hab.,76 m²,Planta 4ª exterior con ascensor,/inmueble/98637619/,"\nPiso situado en la zona de Alfonso XIII, con...",Chamartin,Flat
1,"Piso en pasaje San Pedro, 9, Prosperidad, Madrid",750.0,1 hab.,60 m²,Planta 6ª exterior con ascensor,/inmueble/98538159/,\nLa vivienda tiene cocina independiente y sal...,Chamartin,Flat
2,"Piso en calle de Vinaroz, 16, Ciudad Jardín, M...",925.0,1 hab.,55 m²,Planta 1ª exterior con ascensor,/inmueble/98635897/,"\nApartamento en casa con jardin, proximo al a...",Chamartin,Flat
3,"Piso en calle Rafael Salgado, Bernabéu-Hispano...",2.8,5 hab.,202 m²,Planta 5ª exterior con ascensor,/inmueble/97596364/,\nVIVIR A LO GRANDE EN EL CORAZÓN DE CHAMARTÍN...,Chamartin,Flat
4,"Piso en calle de Pradillo, 13, Ciudad Jardín, ...",1.4,2 hab.,95 m²,Planta 6ª exterior con ascensor,/inmueble/98642139/,\nPrecioso y luminoso piso entre las zonas de ...,Chamartin,Flat
...,...,...,...,...,...,...,...,...,...
558,"Estudio en avenida de la Osa Mayor, 57, Aravac...",750.0,55 m²,Planta 1ª exterior sin ascensor,NaN,/inmueble/91089733/,"\nAire acondicionado, parque recién reformado.\n",Moncloa,Studio
559,"Piso en avenida del Talgo, 220, Aravaca, Madrid",1.8,1 hab.,59 m²,Planta 1ª exterior con ascensor,/inmueble/94651456/,\nPrecioso apartamento recién pintado y listo ...,Moncloa,Flat
560,"Piso en calle San Restituto, 51, Valdezarza, M...",1.8,2 hab.,98 m²,Planta 6ª exterior con ascensor,/inmueble/27957885/,\nCalidades de lujo. 2 dormitorios. Cocina tot...,Moncloa,Flat
561,"Piso en calle Isla de Oza, 76, Ciudad Universi...",1.5,3 hab.,87 m²,Planta 1ª exterior con ascensor,/inmueble/1986527/,\nAbstenerse agencias comunidad incluida en el...,Moncloa,Flat
562,"Piso en calle del Tutor, Argüelles, Madrid",3.4,6 hab.,220 m²,Planta 5ª exterior con ascensor,/inmueble/95275218/,\nTODOS LOS GASTOS INCLUIDOS /MAD Housing alqu...,Moncloa,Flat

# Separate the Studio rows

In [16]:
df_studio = df.loc[(df['Type'] == 'Studio')]

In [17]:
df = df.loc[~(df['Type'] == 'Studio')]

In [18]:
df_studio

,title,price,rooms,mtts,floor,link,description,Distric,Type
169,"Estudio en C. de Irún, Argüelles, Madrid",1.95,37 m²,Planta 2ª exterior con ascensor,NaN,/inmueble/97107458/,\nEste apartamento estará disponible desde el ...,Chamartin,Studio
176,"Estudio en calle Aguarón, Valdemarín, Madrid",900.00,55 m²,Planta 2ª exterior con ascensor,NaN,/inmueble/98588378/,\nChrystie & Didie ofrece en Exclusiva. Loft m...,Chamartin,Studio
178,"Estudio en calle de la Princesa, Argüelles, Ma...",1.30,49 m²,Planta 1ª exterior con ascensor,NaN,/inmueble/98518832/,\nAltor Asesores pone a su disposición exclusi...,Chamartin,Studio
183,"Estudio en calle de la Princesa, Argüelles, Ma...",2.20,35 m²,Planta 20ª exterior con ascensor,NaN,/inmueble/88492589/,\nLuxury Up presenta este lujoso ático decorad...,Chamartin,Studio
190,"Estudio en calle de Irún, Argüelles, Madrid",900.00,72 m²,exterior con ascensor,NaN,/inmueble/98148724/,\n¡ATRACTIVO ESTUDIO EN ALQUILER!\nHousinGo pr...,Chamartin,Studio
...,...,...,...,...,...,...,...,...,...
546,"Estudio en Aravaca, Madrid",650.00,35 m²,Bajo exterior sin ascensor,NaN,/inmueble/91295965/,"\nEstudio de 650 Euros, para vivienda u oficin...",Moncloa,Studio
551,"Estudio en plaza Almuñécar, 9, Casa de Campo, ...",700.00,50 m²,Bajo exterior sin ascensor,NaN,/inmueble/98060957/,"\napartamento recién reformado, muy próximo a ...",Moncloa,Studio
553,"Estudio en calle de Altair, 5, Valdemarín, Madrid",795.00,25 m²,Bajo exterior sin ascensor,NaN,/inmueble/95041156/,\nZona de Valdemarin. alquiler independiente d...,Moncloa,Studio
556,"Estudio en calle de la Princesa, 27, Argüelles...",870.00,38 m²,Planta 20ª exterior con ascensor,NaN,/inmueble/95650469/,\nEstudio muy luminoso situado en planta 20 co...,Moncloa,Studio
558,"Estudio en avenida de la Osa Mayor, 57, Aravac...",750.00,55 m²,Planta 1ª exterior sin ascensor,NaN,/inmueble/91089733/,"\nAire acondicionado, parque recién reformado.\n",Moncloa,Studio

In [19]:
df_studio['floor'] = df_studio['mtts'].values

C:\Users\cex\AppData\Local\Temp\ipykernel_17224\2838602105.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_studio['floor'] = df_studio['mtts'].values

In [20]:
df_studio['mtts'] = df_studio['rooms'].values

C:\Users\cex\AppData\Local\Temp\ipykernel_17224\3931675923.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_studio['mtts'] = df_studio['rooms'].values

In [21]:
df_studio['rooms'] = 0

C:\Users\cex\AppData\Local\Temp\ipykernel_17224\2992163233.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_studio['rooms'] = 0

In [22]:
df_studio

,title,price,rooms,mtts,floor,link,description,Distric,Type
169,"Estudio en C. de Irún, Argüelles, Madrid",1.95,0,37 m²,Planta 2ª exterior con ascensor,/inmueble/97107458/,\nEste apartamento estará disponible desde el ...,Chamartin,Studio
176,"Estudio en calle Aguarón, Valdemarín, Madrid",900.00,0,55 m²,Planta 2ª exterior con ascensor,/inmueble/98588378/,\nChrystie & Didie ofrece en Exclusiva. Loft m...,Chamartin,Studio
178,"Estudio en calle de la Princesa, Argüelles, Ma...",1.30,0,49 m²,Planta 1ª exterior con ascensor,/inmueble/98518832/,\nAltor Asesores pone a su disposición exclusi...,Chamartin,Studio
183,"Estudio en calle de la Princesa, Argüelles, Ma...",2.20,0,35 m²,Planta 20ª exterior con ascensor,/inmueble/88492589/,\nLuxury Up presenta este lujoso ático decorad...,Chamartin,Studio
190,"Estudio en calle de Irún, Argüelles, Madrid",900.00,0,72 m²,exterior con ascensor,/inmueble/98148724/,\n¡ATRACTIVO ESTUDIO EN ALQUILER!\nHousinGo pr...,Chamartin,Studio
...,...,...,...,...,...,...,...,...,...
546,"Estudio en Aravaca, Madrid",650.00,0,35 m²,Bajo exterior sin ascensor,/inmueble/91295965/,"\nEstudio de 650 Euros, para vivienda u oficin...",Moncloa,Studio
551,"Estudio en plaza Almuñécar, 9, Casa de Campo, ...",700.00,0,50 m²,Bajo exterior sin ascensor,/inmueble/98060957/,"\napartamento recién reformado, muy próximo a ...",Moncloa,Studio
553,"Estudio en calle de Altair, 5, Valdemarín, Madrid",795.00,0,25 m²,Bajo exterior sin ascensor,/inmueble/95041156/,\nZona de Valdemarin. alquiler independiente d...,Moncloa,Studio
556,"Estudio en calle de la Princesa, 27, Argüelles...",870.00,0,38 m²,Planta 20ª exterior con ascensor,/inmueble/95650469/,\nEstudio muy luminoso situado en planta 20 co...,Moncloa,Studio
558,"Estudio en avenida de la Osa Mayor, 57, Aravac...",750.00,0,55 m²,Planta 1ª exterior sin ascensor,/inmueble/91089733/,"\nAire acondicionado, parque recién reformado.\n",Moncloa,Studio

In [23]:
new_df_list = [df_studio,df]
df = pd.concat(new_df_list)

In [24]:
df

,title,price,rooms,mtts,floor,link,description,Distric,Type
169,"Estudio en C. de Irún, Argüelles, Madrid",1.95,0,37 m²,Planta 2ª exterior con ascensor,/inmueble/97107458/,\nEste apartamento estará disponible desde el ...,Chamartin,Studio
176,"Estudio en calle Aguarón, Valdemarín, Madrid",900.00,0,55 m²,Planta 2ª exterior con ascensor,/inmueble/98588378/,\nChrystie & Didie ofrece en Exclusiva. Loft m...,Chamartin,Studio
178,"Estudio en calle de la Princesa, Argüelles, Ma...",1.30,0,49 m²,Planta 1ª exterior con ascensor,/inmueble/98518832/,\nAltor Asesores pone a su disposición exclusi...,Chamartin,Studio
183,"Estudio en calle de la Princesa, Argüelles, Ma...",2.20,0,35 m²,Planta 20ª exterior con ascensor,/inmueble/88492589/,\nLuxury Up presenta este lujoso ático decorad...,Chamartin,Studio
190,"Estudio en calle de Irún, Argüelles, Madrid",900.00,0,72 m²,exterior con ascensor,/inmueble/98148724/,\n¡ATRACTIVO ESTUDIO EN ALQUILER!\nHousinGo pr...,Chamartin,Studio
...,...,...,...,...,...,...,...,...,...
557,"Piso en calle de Arcos de la Frontera, 4, Arav...",1.15,2 hab.,55 m²,Planta 1ª exterior con ascensor,/inmueble/91658241/,\nApartamento soleado en Urb. de lujo con pisc...,Moncloa,Flat
559,"Piso en avenida del Talgo, 220, Aravaca, Madrid",1.80,1 hab.,59 m²,Planta 1ª exterior con ascensor,/inmueble/94651456/,\nPrecioso apartamento recién pintado y listo ...,Moncloa,Flat
560,"Piso en calle San Restituto, 51, Valdezarza, M...",1.80,2 hab.,98 m²,Planta 6ª exterior con ascensor,/inmueble/27957885/,\nCalidades de lujo. 2 dormitorios. Cocina tot...,Moncloa,Flat
561,"Piso en calle Isla de Oza, 76, Ciudad Universi...",1.50,3 hab.,87 m²,Planta 1ª exterior con ascensor,/inmueble/1986527/,\nAbstenerse agencias comunidad incluida en el...,Moncloa,Flat
562,"Piso en calle del Tutor, Argüelles, Madrid",3.40,6 hab.,220 m²,Planta 5ª exterior con ascensor,/inmueble/95275218/,\nTODOS LOS GASTOS INCLUIDOS /MAD Housing alqu...,Moncloa,Flat

In [25]:
df[df['Type']=='Studio']

,title,price,rooms,mtts,floor,link,description,Distric,Type
169,"Estudio en C. de Irún, Argüelles, Madrid",1.95,0,37 m²,Planta 2ª exterior con ascensor,/inmueble/97107458/,\nEste apartamento estará disponible desde el ...,Chamartin,Studio
176,"Estudio en calle Aguarón, Valdemarín, Madrid",900.00,0,55 m²,Planta 2ª exterior con ascensor,/inmueble/98588378/,\nChrystie & Didie ofrece en Exclusiva. Loft m...,Chamartin,Studio
178,"Estudio en calle de la Princesa, Argüelles, Ma...",1.30,0,49 m²,Planta 1ª exterior con ascensor,/inmueble/98518832/,\nAltor Asesores pone a su disposición exclusi...,Chamartin,Studio
183,"Estudio en calle de la Princesa, Argüelles, Ma...",2.20,0,35 m²,Planta 20ª exterior con ascensor,/inmueble/88492589/,\nLuxury Up presenta este lujoso ático decorad...,Chamartin,Studio
190,"Estudio en calle de Irún, Argüelles, Madrid",900.00,0,72 m²,exterior con ascensor,/inmueble/98148724/,\n¡ATRACTIVO ESTUDIO EN ALQUILER!\nHousinGo pr...,Chamartin,Studio
...,...,...,...,...,...,...,...,...,...
546,"Estudio en Aravaca, Madrid",650.00,0,35 m²,Bajo exterior sin ascensor,/inmueble/91295965/,"\nEstudio de 650 Euros, para vivienda u oficin...",Moncloa,Studio
551,"Estudio en plaza Almuñécar, 9, Casa de Campo, ...",700.00,0,50 m²,Bajo exterior sin ascensor,/inmueble/98060957/,"\napartamento recién reformado, muy próximo a ...",Moncloa,Studio
553,"Estudio en calle de Altair, 5, Valdemarín, Madrid",795.00,0,25 m²,Bajo exterior sin ascensor,/inmueble/95041156/,\nZona de Valdemarin. alquiler independiente d...,Moncloa,Studio
556,"Estudio en calle de la Princesa, 27, Argüelles...",870.00,0,38 m²,Planta 20ª exterior con ascensor,/inmueble/95650469/,\nEstudio muy luminoso situado en planta 20 co...,Moncloa,Studio
558,"Estudio en avenida de la Osa Mayor, 57, Aravac...",750.00,0,55 m²,Planta 1ª exterior sin ascensor,/inmueble/91089733/,"\nAire acondicionado, parque recién reformado.\n",Moncloa,Studio

# Creating amenities

## Pool

In [26]:
pool = df['description'].str.contains('piscina')
df['Pool'] = pool

In [27]:
df['Pool'].value_counts()

False    3023
True      166
Name: Pool, dtype: int64

## Furniture

In [28]:
furniture = df['description'].str.contains('amueblado')
df['Furniture'] = furniture

In [29]:
df['Furniture'].value_counts()

False    2818
True      371
Name: Furniture, dtype: int64

## Interior or Exterior

In [30]:
exterior = df['floor'].str.contains('exterior')
df['Exterior'] = exterior

In [31]:
df['Exterior'].value_counts()

True     2547
False     631
Name: Exterior, dtype: int64

## Elevator

In [32]:
elevator = df['floor'].str.contains('ascensor')
df['Elevator'] = elevator

In [33]:
df['Elevator'].value_counts()

True     3134
False      44
Name: Elevator, dtype: int64

# Remove non numeric values in rooms , mtts and floor

## Squared meters

In [34]:
df['mtts'] = df['mtts'].str.replace(r'\D', '') # This regex removes all non numeric values
df

C:\Users\cex\AppData\Local\Temp\ipykernel_17224\1551155239.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df['mtts'] = df['mtts'].str.replace(r'\D', '') # This regex removes all non numeric values

,title,price,rooms,mtts,floor,link,description,Distric,Type,Pool,Furniture,Exterior,Elevator
169,"Estudio en C. de Irún, Argüelles, Madrid",1.95,0,37,Planta 2ª exterior con ascensor,/inmueble/97107458/,\nEste apartamento estará disponible desde el ...,Chamartin,Studio,False,False,True,True
176,"Estudio en calle Aguarón, Valdemarín, Madrid",900.00,0,55,Planta 2ª exterior con ascensor,/inmueble/98588378/,\nChrystie & Didie ofrece en Exclusiva. Loft m...,Chamartin,Studio,False,False,True,True
178,"Estudio en calle de la Princesa, Argüelles, Ma...",1.30,0,49,Planta 1ª exterior con ascensor,/inmueble/98518832/,\nAltor Asesores pone a su disposición exclusi...,Chamartin,Studio,False,False,True,True
183,"Estudio en calle de la Princesa, Argüelles, Ma...",2.20,0,35,Planta 20ª exterior con ascensor,/inmueble/88492589/,\nLuxury Up presenta este lujoso ático decorad...,Chamartin,Studio,False,False,True,True
190,"Estudio en calle de Irún, Argüelles, Madrid",900.00,0,72,exterior con ascensor,/inmueble/98148724/,\n¡ATRACTIVO ESTUDIO EN ALQUILER!\nHousinGo pr...,Chamartin,Studio,False,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
557,"Piso en calle de Arcos de la Frontera, 4, Arav...",1.15,2 hab.,55,Planta 1ª exterior con ascensor,/inmueble/91658241/,\nApartamento soleado en Urb. de lujo con pisc...,Moncloa,Flat,True,False,True,True
559,"Piso en avenida del Talgo, 220, Aravaca, Madrid",1.80,1 hab.,59,Planta 1ª exterior con ascensor,/inmueble/94651456/,\nPrecioso apartamento recién pintado y listo ...,Moncloa,Flat,True,False,True,True
560,"Piso en calle San Restituto, 51, Valdezarza, M...",1.80,2 hab.,98,Planta 6ª exterior con ascensor,/inmueble/27957885/,\nCalidades de lujo. 2 dormitorios. Cocina tot...,Moncloa,Flat,False,False,True,True
561,"Piso en calle Isla de Oza, 76, Ciudad Universi...",1.50,3 hab.,87,Planta 1ª exterior con ascensor,/inmueble/1986527/,\nAbstenerse agencias comunidad incluida en el...,Moncloa,Flat,False,False,True,True
562,"Piso en calle del Tutor, Argüelles, Madrid",3.40,6 hab.,220,Planta 5ª exterior con ascensor,/inmueble/95275218/,\nTODOS LOS GASTOS INCLUIDOS /MAD Housing alqu...,Moncloa,Flat,False,False,True,True

## Rooms

In [35]:
df['rooms'] = df['rooms'].str.replace(r'\D', '') # This regex removes all non numeric values
df

C:\Users\cex\AppData\Local\Temp\ipykernel_17224\3841105107.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df['rooms'] = df['rooms'].str.replace(r'\D', '') # This regex removes all non numeric values

,title,price,rooms,mtts,floor,link,description,Distric,Type,Pool,Furniture,Exterior,Elevator
169,"Estudio en C. de Irún, Argüelles, Madrid",1.95,NaN,37,Planta 2ª exterior con ascensor,/inmueble/97107458/,\nEste apartamento estará disponible desde el ...,Chamartin,Studio,False,False,True,True
176,"Estudio en calle Aguarón, Valdemarín, Madrid",900.00,NaN,55,Planta 2ª exterior con ascensor,/inmueble/98588378/,\nChrystie & Didie ofrece en Exclusiva. Loft m...,Chamartin,Studio,False,False,True,True
178,"Estudio en calle de la Princesa, Argüelles, Ma...",1.30,NaN,49,Planta 1ª exterior con ascensor,/inmueble/98518832/,\nAltor Asesores pone a su disposición exclusi...,Chamartin,Studio,False,False,True,True
183,"Estudio en calle de la Princesa, Argüelles, Ma...",2.20,NaN,35,Planta 20ª exterior con ascensor,/inmueble/88492589/,\nLuxury Up presenta este lujoso ático decorad...,Chamartin,Studio,False,False,True,True
190,"Estudio en calle de Irún, Argüelles, Madrid",900.00,NaN,72,exterior con ascensor,/inmueble/98148724/,\n¡ATRACTIVO ESTUDIO EN ALQUILER!\nHousinGo pr...,Chamartin,Studio,False,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
557,"Piso en calle de Arcos de la Frontera, 4, Arav...",1.15,2,55,Planta 1ª exterior con ascensor,/inmueble/91658241/,\nApartamento soleado en Urb. de lujo con pisc...,Moncloa,Flat,True,False,True,True
559,"Piso en avenida del Talgo, 220, Aravaca, Madrid",1.80,1,59,Planta 1ª exterior con ascensor,/inmueble/94651456/,\nPrecioso apartamento recién pintado y listo ...,Moncloa,Flat,True,False,True,True
560,"Piso en calle San Restituto, 51, Valdezarza, M...",1.80,2,98,Planta 6ª exterior con ascensor,/inmueble/27957885/,\nCalidades de lujo. 2 dormitorios. Cocina tot...,Moncloa,Flat,False,False,True,True
561,"Piso en calle Isla de Oza, 76, Ciudad Universi...",1.50,3,87,Planta 1ª exterior con ascensor,/inmueble/1986527/,\nAbstenerse agencias comunidad incluida en el...,Moncloa,Flat,False,False,True,True
562,"Piso en calle del Tutor, Argüelles, Madrid",3.40,6,220,Planta 5ª exterior con ascensor,/inmueble/95275218/,\nTODOS LOS GASTOS INCLUIDOS /MAD Housing alqu...,Moncloa,Flat,False,False,True,True

In [36]:
df['floor'] = df['floor'].str.replace('Bajo','0')

## Floor

In [37]:
df['floor'] = df['floor'].str.replace(r'\D', '') # This regex removes all non numeric values
df

C:\Users\cex\AppData\Local\Temp\ipykernel_17224\3537144436.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df['floor'] = df['floor'].str.replace(r'\D', '') # This regex removes all non numeric values

,title,price,rooms,mtts,floor,link,description,Distric,Type,Pool,Furniture,Exterior,Elevator
169,"Estudio en C. de Irún, Argüelles, Madrid",1.95,NaN,37,2,/inmueble/97107458/,\nEste apartamento estará disponible desde el ...,Chamartin,Studio,False,False,True,True
176,"Estudio en calle Aguarón, Valdemarín, Madrid",900.00,NaN,55,2,/inmueble/98588378/,\nChrystie & Didie ofrece en Exclusiva. Loft m...,Chamartin,Studio,False,False,True,True
178,"Estudio en calle de la Princesa, Argüelles, Ma...",1.30,NaN,49,1,/inmueble/98518832/,\nAltor Asesores pone a su disposición exclusi...,Chamartin,Studio,False,False,True,True
183,"Estudio en calle de la Princesa, Argüelles, Ma...",2.20,NaN,35,20,/inmueble/88492589/,\nLuxury Up presenta este lujoso ático decorad...,Chamartin,Studio,False,False,True,True
190,"Estudio en calle de Irún, Argüelles, Madrid",900.00,NaN,72,,/inmueble/98148724/,\n¡ATRACTIVO ESTUDIO EN ALQUILER!\nHousinGo pr...,Chamartin,Studio,False,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
557,"Piso en calle de Arcos de la Frontera, 4, Arav...",1.15,2,55,1,/inmueble/91658241/,\nApartamento soleado en Urb. de lujo con pisc...,Moncloa,Flat,True,False,True,True
559,"Piso en avenida del Talgo, 220, Aravaca, Madrid",1.80,1,59,1,/inmueble/94651456/,\nPrecioso apartamento recién pintado y listo ...,Moncloa,Flat,True,False,True,True
560,"Piso en calle San Restituto, 51, Valdezarza, M...",1.80,2,98,6,/inmueble/27957885/,\nCalidades de lujo. 2 dormitorios. Cocina tot...,Moncloa,Flat,False,False,True,True
561,"Piso en calle Isla de Oza, 76, Ciudad Universi...",1.50,3,87,1,/inmueble/1986527/,\nAbstenerse agencias comunidad incluida en el...,Moncloa,Flat,False,False,True,True
562,"Piso en calle del Tutor, Argüelles, Madrid",3.40,6,220,5,/inmueble/95275218/,\nTODOS LOS GASTOS INCLUIDOS /MAD Housing alqu...,Moncloa,Flat,False,False,True,True

In [38]:
df['floor'].value_counts()

1     571
2     505
3     389
4     316
5     269
0     263
      251
6     171
7     108
14     56
10     42
8      31
9      30
16     30
20     24
12     24
17     18
11     18
13     12
30     12
26     12
15     12
27      6
34      6
60      1
25      1
Name: floor, dtype: int64

In [39]:
df

,title,price,rooms,mtts,floor,link,description,Distric,Type,Pool,Furniture,Exterior,Elevator
169,"Estudio en C. de Irún, Argüelles, Madrid",1.95,NaN,37,2,/inmueble/97107458/,\nEste apartamento estará disponible desde el ...,Chamartin,Studio,False,False,True,True
176,"Estudio en calle Aguarón, Valdemarín, Madrid",900.00,NaN,55,2,/inmueble/98588378/,\nChrystie & Didie ofrece en Exclusiva. Loft m...,Chamartin,Studio,False,False,True,True
178,"Estudio en calle de la Princesa, Argüelles, Ma...",1.30,NaN,49,1,/inmueble/98518832/,\nAltor Asesores pone a su disposición exclusi...,Chamartin,Studio,False,False,True,True
183,"Estudio en calle de la Princesa, Argüelles, Ma...",2.20,NaN,35,20,/inmueble/88492589/,\nLuxury Up presenta este lujoso ático decorad...,Chamartin,Studio,False,False,True,True
190,"Estudio en calle de Irún, Argüelles, Madrid",900.00,NaN,72,,/inmueble/98148724/,\n¡ATRACTIVO ESTUDIO EN ALQUILER!\nHousinGo pr...,Chamartin,Studio,False,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
557,"Piso en calle de Arcos de la Frontera, 4, Arav...",1.15,2,55,1,/inmueble/91658241/,\nApartamento soleado en Urb. de lujo con pisc...,Moncloa,Flat,True,False,True,True
559,"Piso en avenida del Talgo, 220, Aravaca, Madrid",1.80,1,59,1,/inmueble/94651456/,\nPrecioso apartamento recién pintado y listo ...,Moncloa,Flat,True,False,True,True
560,"Piso en calle San Restituto, 51, Valdezarza, M...",1.80,2,98,6,/inmueble/27957885/,\nCalidades de lujo. 2 dormitorios. Cocina tot...,Moncloa,Flat,False,False,True,True
561,"Piso en calle Isla de Oza, 76, Ciudad Universi...",1.50,3,87,1,/inmueble/1986527/,\nAbstenerse agencias comunidad incluida en el...,Moncloa,Flat,False,False,True,True
562,"Piso en calle del Tutor, Argüelles, Madrid",3.40,6,220,5,/inmueble/95275218/,\nTODOS LOS GASTOS INCLUIDOS /MAD Housing alqu...,Moncloa,Flat,False,False,True,True

# Change the data type for floors

In [40]:
df['floor'].replace('', np.nan, inplace=True)

In [41]:
df = df.dropna(subset=['floor'])

In [42]:
df

,title,price,rooms,mtts,floor,link,description,Distric,Type,Pool,Furniture,Exterior,Elevator
169,"Estudio en C. de Irún, Argüelles, Madrid",1.95,NaN,37,2,/inmueble/97107458/,\nEste apartamento estará disponible desde el ...,Chamartin,Studio,False,False,True,True
176,"Estudio en calle Aguarón, Valdemarín, Madrid",900.00,NaN,55,2,/inmueble/98588378/,\nChrystie & Didie ofrece en Exclusiva. Loft m...,Chamartin,Studio,False,False,True,True
178,"Estudio en calle de la Princesa, Argüelles, Ma...",1.30,NaN,49,1,/inmueble/98518832/,\nAltor Asesores pone a su disposición exclusi...,Chamartin,Studio,False,False,True,True
183,"Estudio en calle de la Princesa, Argüelles, Ma...",2.20,NaN,35,20,/inmueble/88492589/,\nLuxury Up presenta este lujoso ático decorad...,Chamartin,Studio,False,False,True,True
211,"Estudio en calle de Luisa Fernanda, Argüelles,...",700.00,NaN,50,4,/inmueble/91350410/,\nDisponible a principios de septiembre. Alqui...,Chamartin,Studio,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
557,"Piso en calle de Arcos de la Frontera, 4, Arav...",1.15,2,55,1,/inmueble/91658241/,\nApartamento soleado en Urb. de lujo con pisc...,Moncloa,Flat,True,False,True,True
559,"Piso en avenida del Talgo, 220, Aravaca, Madrid",1.80,1,59,1,/inmueble/94651456/,\nPrecioso apartamento recién pintado y listo ...,Moncloa,Flat,True,False,True,True
560,"Piso en calle San Restituto, 51, Valdezarza, M...",1.80,2,98,6,/inmueble/27957885/,\nCalidades de lujo. 2 dormitorios. Cocina tot...,Moncloa,Flat,False,False,True,True
561,"Piso en calle Isla de Oza, 76, Ciudad Universi...",1.50,3,87,1,/inmueble/1986527/,\nAbstenerse agencias comunidad incluida en el...,Moncloa,Flat,False,False,True,True
562,"Piso en calle del Tutor, Argüelles, Madrid",3.40,6,220,5,/inmueble/95275218/,\nTODOS LOS GASTOS INCLUIDOS /MAD Housing alqu...,Moncloa,Flat,False,False,True,True

In [43]:
df['floor'].value_counts()

1     571
2     505
3     389
4     316
5     269
0     263
6     171
7     108
14     56
10     42
8      31
9      30
16     30
20     24
12     24
17     18
11     18
13     12
30     12
26     12
15     12
27      6
34      6
60      1
25      1
Name: floor, dtype: int64

In [44]:
df

,title,price,rooms,mtts,floor,link,description,Distric,Type,Pool,Furniture,Exterior,Elevator
169,"Estudio en C. de Irún, Argüelles, Madrid",1.95,NaN,37,2,/inmueble/97107458/,\nEste apartamento estará disponible desde el ...,Chamartin,Studio,False,False,True,True
176,"Estudio en calle Aguarón, Valdemarín, Madrid",900.00,NaN,55,2,/inmueble/98588378/,\nChrystie & Didie ofrece en Exclusiva. Loft m...,Chamartin,Studio,False,False,True,True
178,"Estudio en calle de la Princesa, Argüelles, Ma...",1.30,NaN,49,1,/inmueble/98518832/,\nAltor Asesores pone a su disposición exclusi...,Chamartin,Studio,False,False,True,True
183,"Estudio en calle de la Princesa, Argüelles, Ma...",2.20,NaN,35,20,/inmueble/88492589/,\nLuxury Up presenta este lujoso ático decorad...,Chamartin,Studio,False,False,True,True
211,"Estudio en calle de Luisa Fernanda, Argüelles,...",700.00,NaN,50,4,/inmueble/91350410/,\nDisponible a principios de septiembre. Alqui...,Chamartin,Studio,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
557,"Piso en calle de Arcos de la Frontera, 4, Arav...",1.15,2,55,1,/inmueble/91658241/,\nApartamento soleado en Urb. de lujo con pisc...,Moncloa,Flat,True,False,True,True
559,"Piso en avenida del Talgo, 220, Aravaca, Madrid",1.80,1,59,1,/inmueble/94651456/,\nPrecioso apartamento recién pintado y listo ...,Moncloa,Flat,True,False,True,True
560,"Piso en calle San Restituto, 51, Valdezarza, M...",1.80,2,98,6,/inmueble/27957885/,\nCalidades de lujo. 2 dormitorios. Cocina tot...,Moncloa,Flat,False,False,True,True
561,"Piso en calle Isla de Oza, 76, Ciudad Universi...",1.50,3,87,1,/inmueble/1986527/,\nAbstenerse agencias comunidad incluida en el...,Moncloa,Flat,False,False,True,True
562,"Piso en calle del Tutor, Argüelles, Madrid",3.40,6,220,5,/inmueble/95275218/,\nTODOS LOS GASTOS INCLUIDOS /MAD Housing alqu...,Moncloa,Flat,False,False,True,True

In [45]:
df['Type'].value_counts()

Flat      2498
Attic      168
Studio     144
Duplex     117
Name: Type, dtype: int64

# Remove the initial words to get the address

In [46]:
df['title'] = df['title'].str.replace('Piso en ','')
df['title'] = df['title'].str.replace('Dúplex en ','')
df['title'] = df['title'].str.replace('Estudio en ','')
df['title'] = df['title'].str.replace('Ático en ','')

C:\Users\cex\AppData\Local\Temp\ipykernel_17224\479815695.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['title'] = df['title'].str.replace('Piso en ','')
C:\Users\cex\AppData\Local\Temp\ipykernel_17224\479815695.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['title'] = df['title'].str.replace('Dúplex en ','')
C:\Users\cex\AppData\Local\Temp\ipykernel_17224\479815695.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['title'] = df['title'].str.replace('Estudio en ','')
C:\Users\cex\AppData\Local\Temp\ipykernel_17224\479815695.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['title'] = df['title'].str.replace('Ático en ','')

In [47]:
df

,title,price,rooms,mtts,floor,link,description,Distric,Type,Pool,Furniture,Exterior,Elevator
169,"C. de Irún, Argüelles, Madrid",1.95,NaN,37,2,/inmueble/97107458/,\nEste apartamento estará disponible desde el ...,Chamartin,Studio,False,False,True,True
176,"calle Aguarón, Valdemarín, Madrid",900.00,NaN,55,2,/inmueble/98588378/,\nChrystie & Didie ofrece en Exclusiva. Loft m...,Chamartin,Studio,False,False,True,True
178,"calle de la Princesa, Argüelles, Madrid",1.30,NaN,49,1,/inmueble/98518832/,\nAltor Asesores pone a su disposición exclusi...,Chamartin,Studio,False,False,True,True
183,"calle de la Princesa, Argüelles, Madrid",2.20,NaN,35,20,/inmueble/88492589/,\nLuxury Up presenta este lujoso ático decorad...,Chamartin,Studio,False,False,True,True
211,"calle de Luisa Fernanda, Argüelles, Madrid",700.00,NaN,50,4,/inmueble/91350410/,\nDisponible a principios de septiembre. Alqui...,Chamartin,Studio,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
557,"calle de Arcos de la Frontera, 4, Aravaca, Madrid",1.15,2,55,1,/inmueble/91658241/,\nApartamento soleado en Urb. de lujo con pisc...,Moncloa,Flat,True,False,True,True
559,"avenida del Talgo, 220, Aravaca, Madrid",1.80,1,59,1,/inmueble/94651456/,\nPrecioso apartamento recién pintado y listo ...,Moncloa,Flat,True,False,True,True
560,"calle San Restituto, 51, Valdezarza, Madrid",1.80,2,98,6,/inmueble/27957885/,\nCalidades de lujo. 2 dormitorios. Cocina tot...,Moncloa,Flat,False,False,True,True
561,"calle Isla de Oza, 76, Ciudad Universitaria, M...",1.50,3,87,1,/inmueble/1986527/,\nAbstenerse agencias comunidad incluida en el...,Moncloa,Flat,False,False,True,True
562,"calle del Tutor, Argüelles, Madrid",3.40,6,220,5,/inmueble/95275218/,\nTODOS LOS GASTOS INCLUIDOS /MAD Housing alqu...,Moncloa,Flat,False,False,True,True

# Remove \n characters on the description

In [48]:
df['description'] = df['description'].astype('string')

C:\Users\cex\AppData\Local\Temp\ipykernel_17224\193056273.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['description'] = df['description'].astype('string')

In [49]:
df

,title,price,rooms,mtts,floor,link,description,Distric,Type,Pool,Furniture,Exterior,Elevator
169,"C. de Irún, Argüelles, Madrid",1.95,NaN,37,2,/inmueble/97107458/,Este apartamento estará disponible desde el 0...,Chamartin,Studio,False,False,True,True
176,"calle Aguarón, Valdemarín, Madrid",900.00,NaN,55,2,/inmueble/98588378/,Chrystie & Didie ofrece en Exclusiva. Loft mu...,Chamartin,Studio,False,False,True,True
178,"calle de la Princesa, Argüelles, Madrid",1.30,NaN,49,1,/inmueble/98518832/,Altor Asesores pone a su disposición exclusiv...,Chamartin,Studio,False,False,True,True
183,"calle de la Princesa, Argüelles, Madrid",2.20,NaN,35,20,/inmueble/88492589/,Luxury Up presenta este lujoso ático decorado...,Chamartin,Studio,False,False,True,True
211,"calle de Luisa Fernanda, Argüelles, Madrid",700.00,NaN,50,4,/inmueble/91350410/,Disponible a principios de septiembre. Alquil...,Chamartin,Studio,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
557,"calle de Arcos de la Frontera, 4, Aravaca, Madrid",1.15,2,55,1,/inmueble/91658241/,Apartamento soleado en Urb. de lujo con pisci...,Moncloa,Flat,True,False,True,True
559,"avenida del Talgo, 220, Aravaca, Madrid",1.80,1,59,1,/inmueble/94651456/,Precioso apartamento recién pintado y listo p...,Moncloa,Flat,True,False,True,True
560,"calle San Restituto, 51, Valdezarza, Madrid",1.80,2,98,6,/inmueble/27957885/,Calidades de lujo. 2 dormitorios. Cocina tota...,Moncloa,Flat,False,False,True,True
561,"calle Isla de Oza, 76, Ciudad Universitaria, M...",1.50,3,87,1,/inmueble/1986527/,Abstenerse agencias comunidad incluida en el ...,Moncloa,Flat,False,False,True,True
562,"calle del Tutor, Argüelles, Madrid",3.40,6,220,5,/inmueble/95275218/,TODOS LOS GASTOS INCLUIDOS /MAD Housing alqui...,Moncloa,Flat,False,False,True,True

# Join the www to the link page

In [50]:
df['link'] = 'www.idealista.com' + df['link'].astype(str)
df

C:\Users\cex\AppData\Local\Temp\ipykernel_17224\879492456.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['link'] = 'www.idealista.com' + df['link'].astype(str)

,title,price,rooms,mtts,floor,link,description,Distric,Type,Pool,Furniture,Exterior,Elevator
169,"C. de Irún, Argüelles, Madrid",1.95,NaN,37,2,www.idealista.com/inmueble/97107458/,Este apartamento estará disponible desde el 0...,Chamartin,Studio,False,False,True,True
176,"calle Aguarón, Valdemarín, Madrid",900.00,NaN,55,2,www.idealista.com/inmueble/98588378/,Chrystie & Didie ofrece en Exclusiva. Loft mu...,Chamartin,Studio,False,False,True,True
178,"calle de la Princesa, Argüelles, Madrid",1.30,NaN,49,1,www.idealista.com/inmueble/98518832/,Altor Asesores pone a su disposición exclusiv...,Chamartin,Studio,False,False,True,True
183,"calle de la Princesa, Argüelles, Madrid",2.20,NaN,35,20,www.idealista.com/inmueble/88492589/,Luxury Up presenta este lujoso ático decorado...,Chamartin,Studio,False,False,True,True
211,"calle de Luisa Fernanda, Argüelles, Madrid",700.00,NaN,50,4,www.idealista.com/inmueble/91350410/,Disponible a principios de septiembre. Alquil...,Chamartin,Studio,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
557,"calle de Arcos de la Frontera, 4, Aravaca, Madrid",1.15,2,55,1,www.idealista.com/inmueble/91658241/,Apartamento soleado en Urb. de lujo con pisci...,Moncloa,Flat,True,False,True,True
559,"avenida del Talgo, 220, Aravaca, Madrid",1.80,1,59,1,www.idealista.com/inmueble/94651456/,Precioso apartamento recién pintado y listo p...,Moncloa,Flat,True,False,True,True
560,"calle San Restituto, 51, Valdezarza, Madrid",1.80,2,98,6,www.idealista.com/inmueble/27957885/,Calidades de lujo. 2 dormitorios. Cocina tota...,Moncloa,Flat,False,False,True,True
561,"calle Isla de Oza, 76, Ciudad Universitaria, M...",1.50,3,87,1,www.idealista.com/inmueble/1986527/,Abstenerse agencias comunidad incluida en el ...,Moncloa,Flat,False,False,True,True
562,"calle del Tutor, Argüelles, Madrid",3.40,6,220,5,www.idealista.com/inmueble/95275218/,TODOS LOS GASTOS INCLUIDOS /MAD Housing alqui...,Moncloa,Flat,False,False,True,True

In [51]:
df['mtts'].value_counts()

60     190
70     167
80     145
100    122
55      91
      ...
517      1
370      1
44       1
136      1
32       1
Name: mtts, Length: 156, dtype: int64

# Changin value types to int

In [52]:
df['rooms'] = df['rooms'].astype(float)

C:\Users\cex\AppData\Local\Temp\ipykernel_17224\1263143969.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['rooms'] = df['rooms'].astype(float)

In [53]:
df['mtts'] = df['mtts'].astype(int)

C:\Users\cex\AppData\Local\Temp\ipykernel_17224\787947773.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['mtts'] = df['mtts'].astype(int)

In [54]:
df['floor'] = df['floor'].astype(int)

C:\Users\cex\AppData\Local\Temp\ipykernel_17224\2732179297.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['floor'] = df['floor'].astype(int)

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2927 entries, 169 to 562
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   title        2927 non-null   object
 1   price        2927 non-null   float64
 2   rooms        2783 non-null   float64
 3   mtts         2927 non-null   int32
 4   floor        2927 non-null   int32
 5   link         2927 non-null   object
 6   description  2926 non-null   string
 7   Distric      2927 non-null   object
 8   Type         2927 non-null   object
 9   Pool         2926 non-null   object
 10  Furniture    2926 non-null   object
 11  Exterior     2927 non-null   object
 12  Elevator     2927 non-null   object
dtypes: float64(2), int32(2), object(8), string(1)
memory usage: 297.3+ KB

# Getting rid of outliers

## Squared meters

In [56]:
df = df[(df.mtts > 15) & (df.mtts < 200)]

In [57]:
df

,title,price,rooms,mtts,floor,link,description,Distric,Type,Pool,Furniture,Exterior,Elevator
169,"C. de Irún, Argüelles, Madrid",1.95,NaN,37,2,www.idealista.com/inmueble/97107458/,Este apartamento estará disponible desde el 0...,Chamartin,Studio,False,False,True,True
176,"calle Aguarón, Valdemarín, Madrid",900.00,NaN,55,2,www.idealista.com/inmueble/98588378/,Chrystie & Didie ofrece en Exclusiva. Loft mu...,Chamartin,Studio,False,False,True,True
178,"calle de la Princesa, Argüelles, Madrid",1.30,NaN,49,1,www.idealista.com/inmueble/98518832/,Altor Asesores pone a su disposición exclusiv...,Chamartin,Studio,False,False,True,True
183,"calle de la Princesa, Argüelles, Madrid",2.20,NaN,35,20,www.idealista.com/inmueble/88492589/,Luxury Up presenta este lujoso ático decorado...,Chamartin,Studio,False,False,True,True
211,"calle de Luisa Fernanda, Argüelles, Madrid",700.00,NaN,50,4,www.idealista.com/inmueble/91350410/,Disponible a principios de septiembre. Alquil...,Chamartin,Studio,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
554,"calle de Romero Robledo, 11, Argüelles, Madrid",1.10,2.0,64,6,www.idealista.com/inmueble/96962799/,ABSTENERSE AGENCIAS. Piso de 2 dormitorios mu...,Moncloa,Flat,False,False,False,True
557,"calle de Arcos de la Frontera, 4, Aravaca, Madrid",1.15,2.0,55,1,www.idealista.com/inmueble/91658241/,Apartamento soleado en Urb. de lujo con pisci...,Moncloa,Flat,True,False,True,True
559,"avenida del Talgo, 220, Aravaca, Madrid",1.80,1.0,59,1,www.idealista.com/inmueble/94651456/,Precioso apartamento recién pintado y listo p...,Moncloa,Flat,True,False,True,True
560,"calle San Restituto, 51, Valdezarza, Madrid",1.80,2.0,98,6,www.idealista.com/inmueble/27957885/,Calidades de lujo. 2 dormitorios. Cocina tota...,Moncloa,Flat,False,False,True,True
561,"calle Isla de Oza, 76, Ciudad Universitaria, M...",1.50,3.0,87,1,www.idealista.com/inmueble/1986527/,Abstenerse agencias comunidad incluida en el ...,Moncloa,Flat,False,False,True,True

## Floor

In [58]:
df = df[df.floor < 7]

In [59]:
df

,title,price,rooms,mtts,floor,link,description,Distric,Type,Pool,Furniture,Exterior,Elevator
169,"C. de Irún, Argüelles, Madrid",1.95,NaN,37,2,www.idealista.com/inmueble/97107458/,Este apartamento estará disponible desde el 0...,Chamartin,Studio,False,False,True,True
176,"calle Aguarón, Valdemarín, Madrid",900.00,NaN,55,2,www.idealista.com/inmueble/98588378/,Chrystie & Didie ofrece en Exclusiva. Loft mu...,Chamartin,Studio,False,False,True,True
178,"calle de la Princesa, Argüelles, Madrid",1.30,NaN,49,1,www.idealista.com/inmueble/98518832/,Altor Asesores pone a su disposición exclusiv...,Chamartin,Studio,False,False,True,True
211,"calle de Luisa Fernanda, Argüelles, Madrid",700.00,NaN,50,4,www.idealista.com/inmueble/91350410/,Disponible a principios de septiembre. Alquil...,Chamartin,Studio,False,False,False,True
251,"calle de Irún, Argüelles, Madrid",900.00,NaN,73,2,www.idealista.com/inmueble/98145156/,"Excelente estudio, junto a la estación de Prí...",Chamartin,Studio,False,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
554,"calle de Romero Robledo, 11, Argüelles, Madrid",1.10,2.0,64,6,www.idealista.com/inmueble/96962799/,ABSTENERSE AGENCIAS. Piso de 2 dormitorios mu...,Moncloa,Flat,False,False,False,True
557,"calle de Arcos de la Frontera, 4, Aravaca, Madrid",1.15,2.0,55,1,www.idealista.com/inmueble/91658241/,Apartamento soleado en Urb. de lujo con pisci...,Moncloa,Flat,True,False,True,True
559,"avenida del Talgo, 220, Aravaca, Madrid",1.80,1.0,59,1,www.idealista.com/inmueble/94651456/,Precioso apartamento recién pintado y listo p...,Moncloa,Flat,True,False,True,True
560,"calle San Restituto, 51, Valdezarza, Madrid",1.80,2.0,98,6,www.idealista.com/inmueble/27957885/,Calidades de lujo. 2 dormitorios. Cocina tota...,Moncloa,Flat,False,False,True,True
561,"calle Isla de Oza, 76, Ciudad Universitaria, M...",1.50,3.0,87,1,www.idealista.com/inmueble/1986527/,Abstenerse agencias comunidad incluida en el ...,Moncloa,Flat,False,False,True,True

## Price

In [60]:
df = df[df.price > 350]

In [61]:
df

,title,price,rooms,mtts,floor,link,description,Distric,Type,Pool,Furniture,Exterior,Elevator
176,"calle Aguarón, Valdemarín, Madrid",900.0,NaN,55,2,www.idealista.com/inmueble/98588378/,Chrystie & Didie ofrece en Exclusiva. Loft mu...,Chamartin,Studio,False,False,True,True
211,"calle de Luisa Fernanda, Argüelles, Madrid",700.0,NaN,50,4,www.idealista.com/inmueble/91350410/,Disponible a principios de septiembre. Alquil...,Chamartin,Studio,False,False,False,True
251,"calle de Irún, Argüelles, Madrid",900.0,NaN,73,2,www.idealista.com/inmueble/98145156/,"Excelente estudio, junto a la estación de Prí...",Chamartin,Studio,False,False,True,True
339,"avenida del Doctor Federico Rubio y Galí, 88, ...",850.0,NaN,41,0,www.idealista.com/inmueble/98614584/,Se alquila estudio amueblado de 40 m2 recién ...,Chamartin,Studio,False,True,True,True
370,"Valdemarín, Madrid",795.0,NaN,42,1,www.idealista.com/inmueble/97899849/,ARAVACA-VALDEMARIN. Exclusivo Loft de 40 M2 s...,Chamartin,Studio,False,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
532,"calle de San Restituto, 53, Valdezarza, Madrid",900.0,1.0,50,3,www.idealista.com/inmueble/92066241/,"Estupendo piso amueblado, con cocina totalmen...",Moncloa,Flat,False,True,True,True
535,"calle Arriaza, 12, Argüelles, Madrid",900.0,1.0,50,3,www.idealista.com/inmueble/29286956/,"Precioso apartamento de un dormitorio, salón,...",Moncloa,Flat,False,False,False,True
547,"Aravaca, Madrid",990.0,2.0,80,0,www.idealista.com/inmueble/96987552/,"Aravaca, estupendo amplio apartamento de 2 do...",Moncloa,Flat,False,False,True,True
548,"Aravaca, Madrid",995.0,2.0,75,0,www.idealista.com/inmueble/98349774/,"OCASION, se alquila apartamento en Aravaca, z...",Moncloa,Flat,False,False,True,True
549,"Valdezarza, Madrid",750.0,1.0,50,6,www.idealista.com/inmueble/86380691/,"""OFERTA ""PUERTA DE HIERRO APARTAMENTO REFORMA...",Moncloa,Flat,False,False,True,True

In [62]:
df['Distric'].value_counts()

La Latina    91
Malasaña     91
Lavapies     87
Chamartin    85
Moncloa      84
Chueca       79
Name: Distric, dtype: int64

In [63]:
df['Type'].value_counts()

Flat      379
Studio     87
Attic      27
Duplex     24
Name: Type, dtype: int64

In [64]:
df.rename(columns = {'title':'Address', 'price':'Price', 'rooms':'Rooms', 'mtts':'Squared_meters' , 'floor' : 'Floor' , 'link':'Link', 'description':'Summary'}, inplace = True)

C:\Users\cex\AppData\Local\Temp\ipykernel_17224\3501980737.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns = {'title':'Address', 'price':'Price', 'rooms':'Rooms', 'mtts':'Squared_meters' , 'floor' : 'Floor' , 'link':'Link', 'description':'Summary'}, inplace = True)

In [65]:
df

,Address,Price,Rooms,Squared_meters,Floor,Link,Summary,Distric,Type,Pool,Furniture,Exterior,Elevator
176,"calle Aguarón, Valdemarín, Madrid",900.0,NaN,55,2,www.idealista.com/inmueble/98588378/,Chrystie & Didie ofrece en Exclusiva. Loft mu...,Chamartin,Studio,False,False,True,True
211,"calle de Luisa Fernanda, Argüelles, Madrid",700.0,NaN,50,4,www.idealista.com/inmueble/91350410/,Disponible a principios de septiembre. Alquil...,Chamartin,Studio,False,False,False,True
251,"calle de Irún, Argüelles, Madrid",900.0,NaN,73,2,www.idealista.com/inmueble/98145156/,"Excelente estudio, junto a la estación de Prí...",Chamartin,Studio,False,False,True,True
339,"avenida del Doctor Federico Rubio y Galí, 88, ...",850.0,NaN,41,0,www.idealista.com/inmueble/98614584/,Se alquila estudio amueblado de 40 m2 recién ...,Chamartin,Studio,False,True,True,True
370,"Valdemarín, Madrid",795.0,NaN,42,1,www.idealista.com/inmueble/97899849/,ARAVACA-VALDEMARIN. Exclusivo Loft de 40 M2 s...,Chamartin,Studio,False,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
532,"calle de San Restituto, 53, Valdezarza, Madrid",900.0,1.0,50,3,www.idealista.com/inmueble/92066241/,"Estupendo piso amueblado, con cocina totalmen...",Moncloa,Flat,False,True,True,True
535,"calle Arriaza, 12, Argüelles, Madrid",900.0,1.0,50,3,www.idealista.com/inmueble/29286956/,"Precioso apartamento de un dormitorio, salón,...",Moncloa,Flat,False,False,False,True
547,"Aravaca, Madrid",990.0,2.0,80,0,www.idealista.com/inmueble/96987552/,"Aravaca, estupendo amplio apartamento de 2 do...",Moncloa,Flat,False,False,True,True
548,"Aravaca, Madrid",995.0,2.0,75,0,www.idealista.com/inmueble/98349774/,"OCASION, se alquila apartamento en Aravaca, z...",Moncloa,Flat,False,False,True,True
549,"Valdezarza, Madrid",750.0,1.0,50,6,www.idealista.com/inmueble/86380691/,"""OFERTA ""PUERTA DE HIERRO APARTAMENTO REFORMA...",Moncloa,Flat,False,False,True,True

In [66]:
#df.to_csv('Output.csv', index = False)
df.to_csv('madrid_idealista.csv', encoding='utf-8', index=False)